// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMSZcKxaBnoGVQP7VtNOXnFAL_xXyE0nw',
    appId: '1:1097085469145:web:5e0b431242ddc5219959c8',
    messagingSenderId: '1097085469145',
    projectId: 'scholar-chat-c87d5',
    authDomain: 'scholar-chat-c87d5.firebaseapp.com',
    storageBucket: 'scholar-chat-c87d5.firebasestorage.app',
    measurementId: 'G-BWDRD6DCKS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0jtNP40YTT7McNtcJNtz0yNledNce5jw',
    appId: '1:1097085469145:android:847eb14025c8153f9959c8',
    messagingSenderId: '1097085469145',
    projectId: 'scholar-chat-c87d5',
    storageBucket: 'scholar-chat-c87d5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUAgD2E3QYNCYmdRkCQndLLyMj0uPSc9Q',
    appId: '1:1097085469145:ios:c1f6426368a10ddf9959c8',
    messagingSenderId: '1097085469145',
    projectId: 'scholar-chat-c87d5',
    storageBucket: 'scholar-chat-c87d5.firebasestorage.app',
    iosBundleId: 'com.example.scholarChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUAgD2E3QYNCYmdRkCQndLLyMj0uPSc9Q',
    appId: '1:1097085469145:ios:c1f6426368a10ddf9959c8',
    messagingSenderId: '1097085469145',
    projectId: 'scholar-chat-c87d5',
    storageBucket: 'scholar-chat-c87d5.firebasestorage.app',
    iosBundleId: 'com.example.scholarChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMSZcKxaBnoGVQP7VtNOXnFAL_xXyE0nw',
    appId: '1:1097085469145:web:22e7dfa89bde32649959c8',
    messagingSenderId: '1097085469145',
    projectId: 'scholar-chat-c87d5',
    authDomain: 'scholar-chat-c87d5.firebaseapp.com',
    storageBucket: 'scholar-chat-c87d5.firebasestorage.app',
    measurementId: 'G-E8LETHG5F1',
  );
}
